_target_: models.MDMTrainer.MDMTrainer

model:
  _target_: models.mdm.MDM
  njoints: 263
  nfeats: 1
  latent_dim: 512
  ff_size: 1024
  num_layers: 8
  num_heads: 4
  dropout: 0.1
  activation: gelu
  clip_version: ViT-B/32
  clip_dim: 768  # 512 for clip, 768 for bert
  text_encoder_type: bert  # clip, bert
  arch: trans_dec  # trans_enc, trans_dec
  emb_trans_dec: False
  cond:
    cond_mode: [text, start, goal]  # [no_cond, text, action, start, goal]
    cond_mask_prob: 0.1
    mask_frames: False
  embed:
    emb_policy: ca # [add, cat, ca]
    pos_embed_max_len: 5000

diffusion:
  _target_: diffusion.respace.SpacedDiffusion
  num_diffusion_timesteps: 50
  timestep_respacing: ""
  beta:
    schedule_name: cosine
    scale_betas: 1.0
  gaussian_diffusion:
    model_mean_type: START_X
    model_var_type: FIXED_SMALL
    loss_type: MSE
    rescale_timesteps: False

optimizer:
  name: adamw
  lr: 1e-4
  weight_decay: 0.
  adam_betas: [0.9, 0.999]

use_ema: True
avg_model_beta: 0.9999
gen_guidance_param: 2.5
schedule_sampler_type: uniform
ckpt_path: ./pretrain/nymeria/model000800000.pt # /home/mahatano/workspace/mdm/output/lr=1e-4_cross-attention_latest_nymeria_pretrain/checkpoints/model_step=000300000.ckpt # ./pretrain/nymeria/model000800000.pt