hydra:
  run:
    dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}/post-train_mdm_cat_lr=1e-5_bs=64

defaults:
  - _self_
  - trainer: mdm_post-train_trainer
  - data: adt_data

seed: 42
dirpath: checkpoints/
train: True
test: False

# Trainer settings
accelerator: gpu
devices: [1]
strategy: auto
max_steps: 600000
save_interval: 10000
log_interval: 1000
ckpt_path: