hydra:
  run:
    dir: ./output/start_goal_add_no_masking

defaults:
  - _self_
  - trainer: mdm_post-train_trainer
  - data: adt_data

seed: 42
dirpath: checkpoints/
train: True
generate: False

# Trainer settings
accelerator: gpu
devices: [1]
strategy: auto
max_steps: 300000
save_interval: 50000
log_interval: 1000
ckpt_path: 