hydra:
  run:
    # dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}/train_mdm_log_mean
    dir: ./output/generation/

defaults:
  - _self_
  - trainer: mdm_trainer
  - data: humanml_data

seed: 42
dirpath: checkpoints/
train: True
test: False

# Trainer settings
accelerator: gpu
devices: [0]
strategy: auto
max_steps: 600000
save_interval: 50000
log_interval: 1000
ckpt_path:
